swagger: "2.0"
info:
  title: "Planning Permission API"
  description: "This API is a resource for County Councils to manage Planning Permission applications for both residential and commericial properties in an efficient manner."
  version: "1.0.0"
host: "localhost:8085"
Access-Control-Allow-Origin: "localhost:8085"
Vary: Origin
#Access-Control-Allow-Credentials: true
basePath: "/api/residential"
tags:
  - name: "planningpermissions"
    description: "Manage all your Planning Permission applications"
schemes:
  - "http"
paths:

  /planningpermissions:
    get:
      tags:
        - "planningpermissions"
      summary: "Returns a list of Planning Permission applications"
      description: "This returns a list of all Planning Permission applications available on the system"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "No Planning Permission Applications have been found."
    post:
      tags:
        - "planningpermissions"
      summary: "Adds a new Planning Permission application to the system"
      description: "This allows the user to upload a new Planning Permission application to the system."
      parameters:
        - in: "body"
          name: "planningPermission"
          description: "The Planning Permission application updated properties."
          schema:
            type: "object"
            required:
              - "applicantFirstName"
              - "applicantLastName"
              - "houseArea"
              - "applicationStatus"
              - "oneOffHousingId"
            properties:
              applicantFirstName:
                type: "string"
              applicantLastName:
                type: "string"
              houseArea:
                type: "number"
                format: "double"
              applicationStatus:
                type: "string"
              oneOffHousingId:
                type: "integer"
            example:
              referenceId: 5
              applicantFirstName: "Joe D."
              applicantLastName: "Bloggs"
              houseArea: 234.5
              applicationStatus: "New Application"
              oneOffHousingId: 1
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Planning Permission Application Type does not exist."
  /planningpermissions/{referenceId}:
    get:
      tags:
        - "planningpermissions"
      summary: "Returns a single Planning Permission application"
      description: "This returns a single Planning Permission application matching the referenceId"
      parameters:
        - in: "path"
          name: "referenceId"
          schema:
            type: "integer"
          required: true
          description: "The unique ID for the Planning Permission application."
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Planning Permission Application does not exist."

    put:
      tags:
        - "planningpermissions"
      summary: "Updates an existing Planning Permission application on the system"
      description: "This allows the user to upload a new Planning Permission application to the system."
      consumes:
        - "application/json"
      parameters:
        - in: "path"
          name: "referenceId"
          type: "integer"
          description: "The referenceId of the Planning Permission application to be updated."
          required: true
        - in: "body"
          name: "planningPermission"
          description: "The Planning Permission application updated properties."
          schema:
            type: "object"
            required:
              - "referenceId"
            properties:
              applicantFirstName:
                type: "string"
              applicantLastName:
                type: "string"
              houseArea:
                type: "number"
                format: "double"
              applicationStatus:
                type: "string"
              oneOffHousingId:
                type: "integer"
            example:
              applicantFirstName: "Joe D."
              applicantLastName: "Bloggs"
              houseArea: 234.5
              applicationStatus: "Further Information"
              oneOffHousingId: 0

      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Planning Permission application does not exist."

    delete:
      tags:
        - "planningpermissions"
      summary: "Deletes a Planning Permission application"
      description: ""
      operationId: "deletePlanningPermissionApplication"
      produces:
        - "application/json"
      parameters:
        - name: "referenceId"
          in: "path"
          description: "Planning Permission application referenceId to delete"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Planning Permission application referenceId: {referenceId} has been deleted"
        "400":
          description: "Invalid referenceId supplied"
        "404":
          description: "application not found"

  /planningpermissions/types?oneOffHousingId={oneOffHousingId}:
    get:
      tags:
        - "planningpermissions"
      summary: "Returns a list of Planning Permission applications"
      description: "This returns list of Planning Permission applications matching the oneOffHousingId. Use 0 for residential applications and 1 for commercial applications."
      parameters:
        - in: "path"
          name: "oneOffHousingId"
          schema:
            type: "integer"
          required: true
          description: "The ID for the type of Planning Permission the application is. Use 0 for residential applications and 1 for commericial applications."
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Planning Permission Application Type does not exist."


